export type { IRBlock, IRMessage, IRRequest, IRResponse, IREvent, IRRole, IRTextBlock, IRThinkingBlock, IRToolUseBlock, IRToolResultBlock, IRToolDef } from './ir/types.js'
export { stableHash, canonicalize } from './ir/hash.js'
export { cacheKey } from './cache/key.js'
export { IdempotencyCache } from './cache/idempotency-cache.js'
export type { CacheStats } from './cache/idempotency-cache.js'
export { classifyError, computeNextWait, PAUSE_AFTER_N_FAILURES, PAUSE_FLOOR_MS } from './retry/policy.js'
export type { ErrorInfo, ErrorAction } from './retry/policy.js'
export { backoffMs, DEFAULT_BACKOFF, OVERLOAD_BACKOFF } from './retry/backoff.js'
export type { BackoffOpts } from './retry/backoff.js'
export { preferredEndpoint, endpointBaseUrl, CONCURRENCY } from './provider/endpoint-map.js'
export type { LLMProvider } from './provider/provider.js'
export { estimateTokens } from './provider/token-count.js'
export { GLMAnthropicProvider } from './provider/glm-anthropic.js'
export { GLMOpenAIProvider } from './provider/glm-openai.js'
export { parseRateHeaders } from './quota/rate-headers.js'
export type { RateHeaders } from './quota/rate-headers.js'
export { POOL_LIMITS } from './quota/pools.js'
export type { Tier, PoolLimit } from './quota/pools.js'
export { QuotaRepo } from './quota/quota-repo.js'
export type { UsageRow, PoolRow } from './quota/quota-repo.js'
export { QuotaTracker } from './quota/quota-tracker.js'
export type { GuardLevel, QuotaSummary } from './quota/quota-tracker.js'
export { CancellationToken } from './service/cancellation.js'
export { PartialBuffer } from './service/call-context.js'
export { LLMService } from './service/llm-service.js'
export type { LLMServiceOpts, RunHandle } from './service/llm-service.js'
export { readSSE } from './stream/sse.js'
export type { SSEEvent, StreamEvent } from './stream/sse.js'
export { parseAnthropicStream } from './stream/anthropic-parser.js'
export { parseOpenAIStream } from './stream/openai-parser.js'
export { coalesce } from './stream/coalesce.js'
export type { CoalescedResult } from './stream/coalesce.js'
export { resolveCredentials } from './credentials/resolver.js'
export type { ResolvedCredentials, ResolveOpts } from './credentials/resolver.js'
export { listProfiles, setActiveProfile } from './credentials/profile.js'
// Side-effect: registers 'llm-router' subsystem with LoaderHub
import './daemon-loader.js'
